server:
  port: 8085

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

spring:
  application:
    name: ORDER-SERVICE


  config:
    import: configserver:http://localhost:8888/
